### ISSUE TITLE
Show more of next item

### ISSUE THREAD

**Issue by alebarbaja** [CodyHouse/cd-carousel-v3-changelog#2]
I set a carousel with the option `data-overflow-items="on"` but on mobile the next item is shown very little. How can I show more? I tried changing the size `carousel-item-auto-size` but if I put a small number, then appears 2 items, and the next items still don't show entirely.

I share an example:
![Screen Recording 2021-03-23 at 10 49 22](https://user-images.githubusercontent.com/28918805/112127354-a6e86b80-8bc5-11eb-893d-bbd7bd63b8a0.gif)

**Comment by claudia-romano** [comment]
Hi there, the `.carousel-v3` element has a class of `container`, so its width is:
`width: calc(100% - 2*var(--component-padding));`

If you want to increase the visible part of the next item, you can reduce this width value. Make sure to keep margin-left/margin-right set to auto so that the carousel is centered.

Cheers!
