### ISSUE TITLE
the --carousel-item-auto-size is overridden in mobile  

### ISSUE THREAD

**Issue by omarherri** [CodyHouse/cd-carousel-v3-changelog#3]
I tried to replace the default value --carousel-item-auto-size value in mobile version. But whenever the second carousel_item doesn't fit anymore in the viewport it scale the first element to 100% width and override the value set in --carousel-item-auto-size.

So if we want to have 2 elements visible, we need to juggle with the width.

**Comment by claudia-romano** [comment]
Hi there, that's actually the expected behaviour. 
The `--carousel-item-auto-size` variable is the minimum width value for each carousel item. If you need to have two elements visible on mobile, then you can set this variable to a small enough value (e.g., 100px) and then increase its value at different media queries. Hope that makes sense!

**Comment by omarherri** [comment]
Ahhh i see thank you for this. I taught it was the default width. I'll give this a try.

**Comment by omarherri** [comment]
Ahhh i see thank you for this. I taught it was the default width. I'll give this a try.
